### ISSUE TITLE
Unable to load custom stylelint config

### ISSUE THREAD

**Issue by iblack10** [mrmlnc/vscode-stylefmt#1] opened 2016-07-21 11:03 UTC
Thanks for creating the plugin.

I have a working ".stylelintrc" config file in the root of my project which successfully lints styles inside of VS Code. However, I can't get vscode-stylefmt to use the same configuration file. When I run style-fmt it just uses some default rules and not the rules in my .stylelintrc file.

Am I missing something?

**Comment by mrmlnc** [comment] 2016-07-21 15:19
Hi, @iblack10,

I can't reproduce your problem on Windows 10. You can provide your configuration file and CSS/Scss file (preferably with the structure of directories)?

**Comment by iblack10** [comment] 2016-07-21 16:06
Ah, I think I've narrowed down the issue to how my stylelint rules are formatted. I have:

"indentation": [4, { "severity": "error" }]

That doesn't work - but this does:

"indentation": 4

I've been using different severities for rules as per the stylelint docs: https://github.com/stylelint/stylelint/blob/d2166dfbcdefefacafd27afd5993ec8341c3b45e/docs/user-guide/configuration.md#severities-error--warning but it seems these are not compatible with stylefmt just now.

**Comment by mrmlnc** [comment] 2016-07-21 16:28
It seems that this is so. I installed Stylefmt as the global package and tried to format a SCSS file with this configuration:

``` json
{
  "rules": {
    "indentation": [4, { "severity": "warning" }]
  }
}
```

And... it does not work as expected. Please create this question in the [repository Stylefmt](https://github.com/morishitter/stylefmt). I will update the plugin, once this issue is resolved.

**Comment by iblack10** [comment] 2016-07-21 16:41
Thanks - have created an [issue](https://github.com/morishitter/stylefmt/issues/170) for this now.

**Comment by mrmlnc** [comment] 2016-07-21 16:45
Ok. In such a case, i will close this issue.  I will update the plugin, once this issue is resolved. :+1:

**Closed as completed by mrmlnc** 2016-07-21 16:45 UTC

**Comment by iblack10** [comment] 2016-07-27 23:50
I've submitted a [pull request](https://github.com/morishitter/stylefmt/pull/171) which should fix this issue for the "indentation" rule. Same process would need to be carried out for all other rules as well though.

**Comment by mrmlnc** [comment] 2016-07-28 08:03
@iblack10, done :+1:
